#!/bin/bash
#SBATCH -N 1
#SBATCH -n 68
#SBATCH -C knl,quad,cache
#SBATCH --job-name=UoI_Debug
#SBATCH --output=./debug/1/stdout.log
#SBATCH --error=./debug/1/stderr.log 
#SBATCH -t 00:5:00
#SBATCH -p debug

module load gsl
module load eigen3
module load cray-hdf5-parallel
module load sde

exe=./uoi
input=/global/cscratch1/sd/akumar25/hcp/rfMRI_zscored.h5
cfile=/global/cscratch1/sd/akumar25/hcp/
sfile=/global/cscratch1/sd/akumar25/hcp/

ngroups=1
n_lambdas=48
selection_thres_frac=1
train_frac_sel=0.9
train_frac_est=0.9
n_boots_sel=48
n_boots_est=48
bagging_options=1

OMP_NUM_THREADS=4
OMP_PROC_BIND=spread

srun -n 68 -c 4 --cpu_bind=threads -u $exe -f $input -v 1 -d 1 --output_coef $cfile --output_scores $sfile -n $ngroups --dataset_matrix /X/data --dataset_vector /y/data --train_frac_sel train_frac_sel --train_frac_est train_frac_est --n_boots_est n_boots_est --n_boots_sel n_boots_sel --bagging_options bagging_options
