#!/bin/bash
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -C knl,quad,cache
#SBATCH --job-name=UoI_Debug
#SBATCH --output=./debug/1/stdout.log
#SBATCH --error=./debug/1/stderr.log 
#SBATCH -t 00:5:00
#SBATCH -p debug

module load gsl
module load eigen3
module load cray-hdf5-parallel
module load sde

#nrnd=1
exe=./uoi
input=/global/cscratch1/sd/mbalasu2/test/coupling.h5
#nbootS=5
#nbootE=5
#output=./Final_Run/coupling/output.h5
#output1=./Final_Run/coupling/lasso.h5
#nMP=8
ngroups=1
#nboot=5


OMP_NUM_THREADS=4
OMP_PROC_BIND=spread


srun -n 2 -c 4 --cpu_bind=threads -u $exe -f $input -v 1 -d 1 --output_coef ./coef_.h5 --output_scores ./scores_.h5 -n $ngroups --dataset_matrix /X/data --dataset_vector /y/data
